worker_processes  1;

events {
   worker_connections 1024;
}

http {

    server {
        listen 80;

        # change if need 
        server_name localhost;

        gzip on;
        gzip_types text/css application/javascript image/svg+xml;
        gzip_vary on;
   
        location / {
            proxy_pass http://acg-master_app:8060;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://acg-master_app:8060;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
