worker_processes  1;

events {
   worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;
    
    server {
        listen 80;
        # change to your domain if need
        server_name localhost;
        
        return 301 https://$server_name$request_uri;
    }

    server {
        listen 443 ssl http2;

        # change to your domain if need
        server_name localhost;

        gzip on;
        gzip_types text/css application/javascript image/svg+xml;
        gzip_vary on;
   
        client_max_body_size 1M;

        # uncomment if you have ssl certificate 
        # ssl
        #        ssl_certificate /etc/nginx/ssl/yourdomain.pem;
        #        ssl_certificate_key /etc/nginx/ssl/yourdomain.key;
        #        
        #        ssl_protocols TLSv1.2 TLSv1.3;
        #        ssl_ciphers HIGH:!aNULL:!MD5;
        #        ssl_prefer_server_ciphers on;
        #        
        #        ssl_session_timeout 1d;
        #        ssl_session_cache shared:SSL:10m;
        #
        location / {
            proxy_pass http://acg-master_app:8060;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/bangumi/anime/ws {
            proxy_pass http://acg-master_app:8060;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_read_timeout 300s;
        }

        location /api/ {
            proxy_pass http://acg-master_app:8060;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 300s;
            proxy_send_timeout 300s;

            limit_req zone=api_limit burst=20 nodelay;
            limit_conn conn_limit 8;
        }
    }
}
